config/routes.rb
Rails.application.routes.draw do
  resources :chats
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :libros
  root 'libros#index'
  resources :documentos
  resources :alumnos
  resources :docentes

end

app/models/docente.rb
class Docente < ActiveRecord::Base
end

app/controllers/docentes_controller.rb
class DocentesController < ApplicationController
  before_action :set_docente, only: [:show, :edit, :update, :destroy]

  # GET /docentes
  # GET /docentes.json
  def index
    @docentes = Docente.all
  end

  # GET /docentes/1
  # GET /docentes/1.json
  def show
  end

  # GET /docentes/new
  def new
    @docente = Docente.new
  end

  # GET /docentes/1/edit
  def edit
  end

  # POST /docentes
  # POST /docentes.json
  def create
    @docente = Docente.new(docente_params)

    respond_to do |format|
      if @docente.save
        format.html { redirect_to @docente, notice: 'Docente was successfully created.' }
        format.json { render :show, status: :created, location: @docente }
      else
        format.html { render :new }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docentes/1
  # PATCH/PUT /docentes/1.json
  def update
    respond_to do |format|
      if @docente.update(docente_params)
        format.html { redirect_to @docente, notice: 'Docente was successfully updated.' }
        format.json { render :show, status: :ok, location: @docente }
      else
        format.html { render :edit }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docentes/1
  # DELETE /docentes/1.json
  def destroy
    @docente.destroy
    respond_to do |format|
      format.html { redirect_to docentes_url, notice: 'Docente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_docente
      @docente = Docente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def docente_params
      params.require(:docente).permit(:Nombre, :Clase, :Asistio, :Descripcion, :Fecha)
    end
end

app/helpers/docentes_helper.rb
module DocentesHelper
end

app/views/docentes/_form.html.erb
<%= form_for(@docente) do |f| %>
  <% if @docente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@docente.errors.count, "error") %> prohibited this docente from being saved:</h2>

      <ul>
      <% @docente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :Nombre %>
  </div>
  <div class="field">
    <%= f.label :Clase %><br>
    <%= f.text_field :Clase %>
  </div>
  <div class="field">
    <%= f.label :Asistio %><br>
    <%= f.check_box :Asistio %>
  </div>
  <div class="field">
    <%= f.label :Descripcion %><br>
    <%= f.text_area :Descripcion %>
  </div>
  <div class="field">
    <%= f.label :Fecha %><br>
    <%= f.datetime_select :Fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/docentes/edit.html.erb
<h1>Editing Docente</h1>

<%= render 'form' %>

<%= link_to 'Show', @docente %> |
<%= link_to 'Back', docentes_path %>

app/views/docentes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Docentes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Clase</th>
      <th>Asistio</th>
      <th>Descripcion</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @docentes.each do |docente| %>
      <tr>
        <td><%= docente.Nombre %></td>
        <td><%= docente.Clase %></td>
        <td><%= docente.Asistio %></td>
        <td><%= docente.Descripcion %></td>
        <td><%= docente.Fecha %></td>
        <td><%= link_to 'Show', docente %></td>
        <td><%= link_to 'Edit', edit_docente_path(docente) %></td>
        <td><%= link_to 'Destroy', docente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Docente', new_docente_path %>

app/views/docentes/new.html.erb
<h1>New Docente</h1>

<%= render 'form' %>

<%= link_to 'Back', docentes_path %>

app/views/docentes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @docente.Nombre %>
</p>

<p>
  <strong>Clase:</strong>
  <%= @docente.Clase %>
</p>

<p>
  <strong>Asistio:</strong>
  <%= @docente.Asistio %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @docente.Descripcion %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @docente.Fecha %>
</p>

<%= link_to 'Edit', edit_docente_path(@docente) %> |
<%= link_to 'Back', docentes_path %>