config/routes.rb
Rails.application.routes.draw do
  resources :chats
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :libros
  root 'libros#index'
  resources :documentos
  resources :alumnos
  resources :docentes

end

app/models/documento.rb
class Documento < ActiveRecord::Base
mount_uploader :Mi_archivo, FileUploader
end

app/controllers/documentos_controller.rb
class DocumentosController < ApplicationController
  before_action :set_documento, only: [:show, :edit, :update, :destroy]

  # GET /documentos
  # GET /documentos.json
  def index
    @documentos = Documento.all
  end

  # GET /documentos/1
  # GET /documentos/1.json
  def show
  end

  # GET /documentos/new
  def new
    @documento = Documento.new
  end

  # GET /documentos/1/edit
  def edit
  end

  # POST /documentos
  # POST /documentos.json
  def create
    @documento = Documento.new(documento_params)
    @documento.Mi_archivo = params[:file]
    respond_to do |format|
      if @documento.save
        format.html { redirect_to @documento, notice: 'Documento was successfully created.' }
        format.json { render :show, status: :created, location: @documento }
      else
        format.html { render :new }
        format.json { render json: @documento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documentos/1
  # PATCH/PUT /documentos/1.json
  def update
    respond_to do |format|
      if @documento.update(documento_params)
        format.html { redirect_to @documento, notice: 'Documento was successfully updated.' }
        format.json { render :show, status: :ok, location: @documento }
      else
        format.html { render :edit }
        format.json { render json: @documento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documentos/1
  # DELETE /documentos/1.json
  def destroy
    @documento.destroy
    respond_to do |format|
      format.html { redirect_to documentos_url, notice: 'Documento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_documento
      @documento = Documento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def documento_params
      params.require(:documento).permit(:Nombre, :Mi_archivo, :Fecha)
    end
end

app/helpers/documentos_helper.rb
module DocumentosHelper
end

app/views/documentos/_form.html.erb
<%= form_for(@documento) do |f| %>
  <% if @documento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@documento.errors.count, "error") %> prohibited this documento from being saved:</h2>

      <ul>
      <% @documento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :Nombre %>
  </div>
  <div class="field">
    <%= f.label :Mi_archivo %><br>
    <%= f.file_field :Mi_archivo %>
  </div>
  <div class="field">
    <%= f.label :Fecha %><br>
    <%= f.datetime_select :Fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documentos/edit.html.erb
<h1>Editing Documento</h1>

<%= render 'form' %>

<%= link_to 'Show', @documento %> |
<%= link_to 'Back', documentos_path %>

app/views/documentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Documentos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Mi archivo</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documentos.each do |documento| %>
      <tr>
        <td><%= documento.Nombre %></td>
        <td><a href="<%= documento.Mi_archivo %>">Download</a></td>
        <td><%= documento.Fecha %></td>
        <td><%= link_to 'Show', documento %></td>
        <td><%= link_to 'Edit', edit_documento_path(documento) %></td>
        <td><%= link_to 'Destroy', documento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Documento', new_documento_path %>

app/views/documentos/new.html.erb
<h1>New Documento</h1>

<%= render 'form' %>

<%= link_to 'Back', documentos_path %>

app/views/documentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @documento.Nombre %>
</p>

<p>
  <strong>Mi archivo:</strong>
  <%= @documento.Mi_archivo %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @documento.Fecha %>
</p>

<%= link_to 'Edit', edit_documento_path(@documento) %> |
<%= link_to 'Back', documentos_path %>