config/routes.rb
Rails.application.routes.draw do
  resources :chats
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :libros
  root 'libros#index'
  resources :documentos
  resources :alumnos
  resources :docentes

end

app/models/libro.rb
class Libro < ActiveRecord::Base
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy]

  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.all
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url, notice: 'Libro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libro_params
      params.require(:libro).permit(:Nnombre, :Autor, :Precio, :Descripcion, :Fecha)
    end
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/libros/_form.html.erb
<%= form_for(@libro) do |f| %>
  <% if @libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
      <% @libro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nnombre %><br>
    <%= f.text_field :Nnombre %>
  </div>
  <div class="field">
    <%= f.label :Autor %><br>
    <%= f.text_field :Autor %>
  </div>
  <div class="field">
    <%= f.label :Precio %><br>
    <%= f.number_field :Precio %>
  </div>
  <div class="field">
    <%= f.label :Descripcion %><br>
    <%= f.text_area :Descripcion %>
  </div>
  <div class="field">
    <%= f.label :Fecha %><br>
    <%= f.datetime_select :Fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libros/edit.html.erb
<h1>Editing Libro</h1>

<%= render 'form' %>

<%= link_to 'Show', @libro %> |
<%= link_to 'Back', libros_path %>

app/views/libros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Libros</h1>

<table>
  <thead>
    <tr>
      <th>Nnombre</th>
      <th>Autor</th>
      <th>Precio</th>
      <th>Descripcion</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libros.each do |libro| %>
      <tr>
        <td><%= libro.Nnombre %></td>
        <td><%= libro.Autor %></td>
        <td><%= libro.Precio %></td>
        <td><%= libro.Descripcion %></td>
        <td><%= libro.Fecha %></td>
        <td><%= link_to 'Show', libro %></td>
        <td><%= link_to 'Edit', edit_libro_path(libro) %></td>
        <td><%= link_to 'Destroy', libro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Libro', new_libro_path %>

app/views/libros/new.html.erb
<h1>New Libro</h1>

<%= render 'form' %>

<%= link_to 'Back', libros_path %>

app/views/libros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nnombre:</strong>
  <%= @libro.Nnombre %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @libro.Autor %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @libro.Precio %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @libro.Descripcion %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @libro.Fecha %>
</p>

<%= link_to 'Edit', edit_libro_path(@libro) %> |
<%= link_to 'Back', libros_path %>